version: '3.8'

services:
  graphdb:
    image: ontotext/graphdb:10.7.0
    container_name: GraphDB
    ports:
      - "7200:7200"
    volumes:
      - ./data:/opt/graphdb/home
    environment:
      - GRAPHDB_HOME=/opt/graphdb/home
      - GDB_HEAP_SIZE=2G